### ISSUE TITLE
Creation of remote copy group with local and remote cpg set fails with 'unknown type string requested for local_user_cpg' error

### ISSUE THREAD

**Issue by leenaj0hn** [farhan7500/hpe3par_ansible_module#7]
Create RCG group with local and remote user and snap CPG set.  The playbook fails with error message
"msg": "implementation error: unknown type string requested for local_user_cpg

**Comment by farhan7500** [comment]
Fixed!

Kindly verify

**Comment by leenaj0hn** [comment]
Verified issue. Closing bug
